### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by wasade** [PriceLab/TReNA#1]
...so far unable to get them to work. Using R 3.2.2 right now but assuming that is not the issue as it's within a micro release of stated req. glmnet was successfully installed prior to sourcing

``` bash
(py35-base)10:00:50 (daniel@sandbar):TReNA@master$ R CMD BUILD .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘TReNA’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘TReNA_0.99.2.tar.gz’

(py35-base)10:01:05 (daniel@sandbar):TReNA@master$ R

...snip...

> source("inst/unitTests/test_TReNA.R")
Error in library(TReNA) : there is no package called ‘TReNA’
>
```

**Comment by marichards** [comment]
I think this is far in the past at this point....we've been able to install TReNA successfully on a number of new machines, both MAC OS and Linux.
