### ISSUE TITLE
more install dependancies

### ISSUE THREAD

**Issue by bheavner** [PriceLab/TReNA#2]
"Error in library(RUnit) : there is no package called ‘RUnit’"

**Comment by bheavner** [comment]
(easily resolved by installing the package, but the dependency isn't mentioned in the readme)

**Comment by paul-shannon** [comment]
source(“http://bioconductor.org/biocLite.R”)
biocLite(“RUnit”)

**Comment by bheavner** [comment]
Is that preferable to 
install.packages("RUnit") ?


I did that, then...

```
> runTests()
[1] --- test_emptyConstructor
[1] --- test_developAndFitDummyTestData
[1] --- test_fitDummyData
[1] begining cross-validation for glmnet, using 10 tfs, target gene.01
[1] glmnet fit with lambda 1.346926
[1] TRUE
```

**Comment by paul-shannon** [comment]
always preferable!  It runs on top of install.packages, adds considerable ease.

**Comment by marichards** [comment]
Closing this...RUnit is included in the "Suggests" portion of the DESCRIPTION file, which is the proper place for it.
