### ISSUE TITLE
warning suggestion for solvers

### ISSUE THREAD

**Issue by paul-shannon** [PriceLab/trena#7]
We now see:

````Warning message:
In run(solver) :
     Signal strength of individual solvers is insufficient for adding
composite scores. Try increasing your sample size
````
Better, I think, is this:

     The signal strength of the ensemble of solvers is too weak
     to support composite scores (“pcaMax” and “concordance” in 
     the model output table).  This is a classic “large n, small m”
     problem rectified by providing more samples.

**Comment by marichards** [comment]
This has been changed to the new warning
